"""
Chart string tables (i18n).

All user-visible text in the generated chart is looked up from this dict,
keyed by language code. Add a new key here to support another language,
then pass it with --lang.
"""

CHART_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        # Figure title
        "title":             "Monte Carlo Simulation",
        # Parameters panel labels
        "param_file":        "File",
        "param_format":      "Format",
        "param_target":      "Target",
        "param_mix":         "Mix",
        "param_duration":    "Duration",
        "param_workdays":    "Work days",
        "param_holidays":    "Days off",
        "param_unplanned":   "Unplanned",
        "param_window":      "Hist. window",
        "param_chart":       "Chart",
        "param_certainties": "Certainties",
        "param_simulations": "Simulations",
        "param_annotations": "Annotations",
        # Parameters panel values
        "window_full":       "full",
        "window_range":      "{start} to {end}",
        "display_all":       "all",
        "none_val":          "none",
        "weeks_abbr":        "w.",        # long form (e.g. "12 w.")
        "weeks_short":       "w",         # short form used inside labels (e.g. "3.0w")
        "days_abbr":         "d.",
        # Size names (must parallel SCORES key order)
        "size_tiny":         "X-Small",
        "size_small":        "Small",
        "size_medium":       "Medium",
        "size_large":        "Large",
        "size_xlarge":       "X-Large",
        # Chart 1 — weeks distribution
        "ax1_title":         "Distribution of weeks required\n({pct:.1f}% of {n:,} simulations reach the target)",
        "ax1_xlabel":        "Weeks required to deliver the target",
        "ax1_ylabel":        "Number of simulations",
        "ax1_objective":     "Target\n{n}w",
        # Chart 2 — volume distribution
        "ax2_title":         "Volume delivered in {n_weeks} weeks ({n_workdays} work days)\n({pct:.1f}% of {n:,} simulations reach the target)",
        "ax2_xlabel":        "Points delivered in {n_weeks} weeks",
        "ax2_ylabel":        "Number of simulations",
        "ax2_target":        "Target\n{target:g} pts",
        # Chart 3 — sensitivity
        "ax3_title":         "Sensitivity to history window\n(deliver {target:g} pts in {n_weeks} w.)",
        "ax3_xlabel":        "History window (weeks) — left: full history, right: recent only",
        "ax3_ylabel":        "Probability of delivering target (%)",
        "ax3_bar_ylabel":    "Throughput (pts / week)",
        "all_label":         "All",
        "active_marker":     "↑ {n}w",
        "active_marker_all": "↑ All",
        "no_data":           "Insufficient data",
        # Console messages
        "console_config_header":      "Configuration",
        "console_formats_header":     "Supported data formats:",
        "console_sim_start":          "Sim. start",
        "console_monday_suffix":      "(Monday)",
        "console_weeks_word":         "weeks",
        "console_days_word":          "days",
        "console_until":              "until {date}",
        "console_source_weeks_label": "Source weeks",
        "console_source_weeks":       "{n} wk., avg. throughput: {avg:.1f} pts/wk.",
        "console_running":            "Running {n:,} simulations…",
        "console_certainty_line":     "{p:3d}% : deliver target in ≤ {val:.1f} weeks",
        "console_probability":        "Probability of delivering in ≤ {n} wk.: {pct:.1f}%",
        "console_annotations_loaded": "{n} annotation date(s) loaded",
        "console_direct_pts":         "{n} direct pts",
        "console_file_not_found":     "File not found: {path}",
        "console_no_data_file":       "No data file found ({a} or {b}).",
        "console_no_valid_data_file": "No valid data file found.",
        "console_invalid_date":       "Invalid date format.",
        "console_zero_workdays":      "Work day count is zero or negative.",
        "console_could_not_load":     "Could not load throughput data.",
        "console_chart_saved":        "Chart saved: {path}",
    },
    "fr": {
        # Titre de la figure
        "title":             "Simulation Monte Carlo",
        # Étiquettes du panneau de paramètres
        "param_file":        "Fichier",
        "param_format":      "Format",
        "param_target":      "Cible",
        "param_mix":         "Mix",
        "param_duration":    "Durée",
        "param_workdays":    "Jours trav.",
        "param_holidays":    "Jours off",
        "param_unplanned":   "Non planifié",
        "param_window":      "Fenêtre hist.",
        "param_chart":       "Graphique",
        "param_certainties": "Certitudes",
        "param_simulations": "Simulations",
        "param_annotations": "Annotations",
        # Valeurs du panneau de paramètres
        "window_full":       "complète",
        "window_range":      "{start} au {end}",
        "display_all":       "tout",
        "none_val":          "aucun",
        "weeks_abbr":        "sem.",
        "weeks_short":       "s",
        "days_abbr":         "j.",
        # Noms des tailles (parallèle aux clés de SCORES)
        "size_tiny":         "Très petit",
        "size_small":        "Petit",
        "size_medium":       "Moyen",
        "size_large":        "Grand",
        "size_xlarge":       "Très grand",
        # Graphique 1 — distribution des semaines
        "ax1_title":         "Distribution du nombre de semaines requises\n({pct:.1f} % des {n:,} simulations atteignent la cible)",
        "ax1_xlabel":        "Semaines requises pour livrer la cible",
        "ax1_ylabel":        "Nombre de simulations",
        "ax1_objective":     "Objectif\n{n}s",
        # Graphique 2 — distribution du volume
        "ax2_title":         "Distribution du volume livré en {n_weeks} semaines ({n_workdays} j. trav.)\n({pct:.1f} % des {n:,} simulations atteignent la cible)",
        "ax2_xlabel":        "Points livrés en {n_weeks} semaines",
        "ax2_ylabel":        "Nombre de simulations",
        "ax2_target":        "Cible\n{target:g} pts",
        # Graphique 3 — sensibilité
        "ax3_title":         "Sensibilité à la fenêtre d'historique\n(livrer {target:g} pts en {n_weeks} sem.)",
        "ax3_xlabel":        "Fenêtre d'historique (semaines) — gauche : tout l'historique, droite : récent seulement",
        "ax3_ylabel":        "Probabilité de livrer la cible (%)",
        "ax3_bar_ylabel":    "Throughput (pts / semaine)",
        "all_label":         "Tout",
        "active_marker":     "↑ {n}s",
        "active_marker_all": "↑ Tout",
        "no_data":           "Données insuffisantes",
        # Messages console
        "console_config_header":      "Configuration",
        "console_formats_header":     "Formats de données pris en charge :",
        "console_sim_start":          "Début sim.",
        "console_monday_suffix":      "(lundi)",
        "console_weeks_word":         "semaines",
        "console_days_word":          "jours",
        "console_until":              "jusqu'au {date}",
        "console_source_weeks_label": "Sem. sources",
        "console_source_weeks":       "{n} sem., débit moyen : {avg:.1f} pts/sem.",
        "console_running":            "Exécution de {n:,} simulations…",
        "console_certainty_line":     "{p:3d} % : livrer la cible en ≤ {val:.1f} sem.",
        "console_probability":        "Probabilité de livrer en ≤ {n} sem. : {pct:.1f} %",
        "console_annotations_loaded": "{n} date(s) d'annotation chargée(s)",
        "console_direct_pts":         "{n} pts directs",
        "console_file_not_found":     "Fichier introuvable : {path}",
        "console_no_data_file":       "Aucun fichier de données trouvé ({a} ou {b}).",
        "console_no_valid_data_file": "Aucun fichier de données valide trouvé.",
        "console_invalid_date":       "Format de date invalide.",
        "console_zero_workdays":      "Le nombre de jours ouvrables est nul ou négatif.",
        "console_could_not_load":     "Impossible de charger les données de débit.",
        "console_chart_saved":        "Graphique enregistré : {path}",
    },
}
